<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTablePaises extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('paises', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name', 200);
            $table->tinyInteger('active')->default(1);
            $table->timestamps();
        });

        DB::table('paises')->insert([
            ['name' => 'Afganistán' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Islas Gland' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Albania' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Alemania' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Andorra' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Angola' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Anguilla' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Antártida' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Antigua y Barbuda' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Antillas Holandesas' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Arabia Saudí' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Argelia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Argentina' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Armenia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Aruba' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Australia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Austria' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Azerbaiyán' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Bahamas' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Bahréin' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Bangladesh' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Barbados' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Bielorrusia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Bélgica' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Belice' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Benin' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Bermudas' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Bhután' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Bolivia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Bosnia y Herzegovina' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Botsuana' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Isla Bouvet' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Brasil' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Brunéi' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Bulgaria' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Burkina Faso' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Burundi' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Cabo Verde' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Islas Caimán' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Camboya' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Camerún' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Canadá' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'República Centroafricana' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Chad' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'República Checa' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Chile' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'China' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Chipre' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Isla de Navidad' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Ciudad del Vaticano' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Islas Cocos' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Colombia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Comoras' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'República Democrática del Congo' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Congo' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Islas Cook' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Corea del Norte' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Corea del Sur' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Costa de Marfil' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Costa Rica' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Croacia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Cuba' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Dinamarca' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Dominica' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'República Dominicana' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Ecuador' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Egipto' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'El Salvador' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Emiratos Árabes Unidos' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Eritrea' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Eslovaquia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Eslovenia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'España' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Islas ultramarinas de Estados Unidos' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Estados Unidos' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Estonia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Etiopía' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Islas Feroe' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Filipinas' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Finlandia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Fiyi' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Francia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Gabón' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Gambia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Georgia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Islas Georgias del Sur y Sandwich del Sur' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Ghana' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Gibraltar' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Granada' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Grecia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Groenlandia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Guadalupe' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Guam' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Guatemala' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Guayana Francesa' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Guinea' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Guinea Ecuatorial' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Guinea-Bissau' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Guyana' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Haití' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Islas Heard y McDonald' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Honduras' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Hong Kong' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Hungría' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'India' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Indonesia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Irán' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Iraq' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Irlanda' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Islandia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Israel' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Italia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Jamaica' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Japón' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Jordania' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Kazajstán' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Kenia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Kirguistán' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Kiribati' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Kuwait' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Laos' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Lesotho' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Letonia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Líbano' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Liberia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Libia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Liechtenstein' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Lituania' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Luxemburgo' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Macao' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'ARY Macedonia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Madagascar' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Malasia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Malawi' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Maldivas' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Malí' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Malta' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Islas Malvinas' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Islas Marianas del Norte' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Marruecos' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Islas Marshall' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Martinica' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Mauricio' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Mauritania' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Mayotte' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'México' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Micronesia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Moldavia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Mónaco' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Mongolia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Montserrat' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Mozambique' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Myanmar' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Namibia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Nauru' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Nepal' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Nicaragua' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Níger' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Nigeria' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Niue' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Isla Norfolk' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Noruega' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Nueva Caledonia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Nueva Zelanda' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Omán' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Países Bajos' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Pakistán' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Palau' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Palestina' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Panamá' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Papúa Nueva Guinea' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Paraguay' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Perú' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Islas Pitcairn' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Polinesia Francesa' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Polonia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Portugal' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Puerto Rico' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Qatar' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Reino Unido' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Reunión' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Ruanda' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Rumania' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Rusia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Sahara Occidental' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Islas Salomón' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Samoa' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Samoa Americana' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'San Cristóbal y Nevis' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'San Marino' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'San Pedro y Miquelón' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'San Vicente y las Granadinas' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Santa Helena' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Santa Lucía' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Santo Tomé y Príncipe' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Senegal' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Serbia y Montenegro' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Seychelles' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Sierra Leona' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Singapur' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Siria' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Somalia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Sri Lanka' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Suazilandia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Sudáfrica' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Sudán' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Suecia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Suiza' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Surinam' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Svalbard y Jan Mayen' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Tailandia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Taiwán' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Tanzania' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Tayikistán' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Territorio Británico del Océano Índico' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Territorios Australes Franceses' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Timor Oriental' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Togo' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Tokelau' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Tonga' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Trinidad y Tobago' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Túnez' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Islas Turcas y Caicos' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Turkmenistán' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Turquía' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Tuvalu' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Ucrania' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Uganda' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Uruguay' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Uzbekistán' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Vanuatu' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Venezuela' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Vietnam' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Islas Vírgenes Británicas' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Islas Vírgenes de los Estados Unidos' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Wallis y Futuna' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Yemen' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Yibuti' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Zambia' , 'created_at' => NOW(), 'updated_at' => NOW()],
            ['name' => 'Zimbabue' , 'created_at' => NOW(), 'updated_at' => NOW()],
           
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('paises');
    }
}
